### ISSUE TITLE
How is the code in this repo licensed? 

### ISSUE THREAD

**Issue by gmonair** [open-ic/open-storage#100]
Hi, there are a lot of cool features in this repo, especially in the /libraries folder. I was wondering if I could use some of the code in my canisters, for the hackathon. Is this allowed? Would it be possible to add LICENSE file(s), so we can check what parts can be used, and how? 

Thanks!

**Comment by domwoe** [comment]
License has been added.

**Comment by gmonair** [comment]
Thank you!
