### ISSUE TITLE
Stop canister failed, 403 Forbidden, how can i fix it

### ISSUE THREAD

**Issue by himyyy** [open-ic/open-storage#80]
thread 'main' panicked at 'Failed to stop canister: HttpError(Http Error: status 403 Forbidden, content type "", content: Requested canister rejected the message)', backend/libraries/canister_client/src/operations/upgrade_service_canisters.rs:53:10

**Comment by GLicDEV** [comment]
Are you calling stop from the controller of that canister? If you use a wallet make sure to issue the command with --no-wallet, so your call "comes from" the dfx identity (hopefully the controller of the canister) and not from your wallet.

**Comment by himyyy** [comment]
> Are you calling stop from the controller of that canister? If you use a wallet make sure to issue the command with --no-wallet, so your call "comes from" the dfx identity (hopefully the controller of the canister) and not from your wallet.

Thanks, i have figure it out. The identity of caller is not the canister's controller.
